---
# Inspired by https://github.com/TechDufus/dotfiles
# This structure is used to bootstrap and configure all homelab hosts consistently.
# Step 1: Ensure all hosts are ready for Ansible management (timezone, base packages, sudo access, etc.)
# Step 2: Apply common roles (e.g., base setup, user management)

- name: Prepare for Base | All your base are belong to us
  hosts: all
  gather_facts: true
  become: true
  tags: base

  # This pre_task checks whether the current host is a WSL environment.
  # Some roles rely on the variable `ansible_host_environment_is_wsl` to apply platform-specific logic.
  pre_tasks:
    - name: Detect if host is WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags: always

  roles:
    - base
