---
###
### Base (for every machine)
###
- name: Prepare for Base | All your base are belong to us
  hosts: all
  gather_facts: true
  tags: base
  become: true
  roles:
    - base

###
### Only workstations
###
#- name: Prepare all tasks for only Workstations
#  hosts: workstations
#tags: workstations
#become: true
#roles:
#  - workstations

###
### Only proxmox
###
#- name: Prepare all tasks for only Proxmox servers
#  hosts: proxmox
#tags: proxmox
#become: true
#roles:
#  - proxmox

###
### All Servers
###
#- name: Prepare all tasks for only Servers
#  hosts: servers
# tags: servers
#become: true
#roles:
#  - servers

###
### end of run cleanup and reporting
###
- name: Finalizing | Cleanup the package cache and remove orphan packages
  hosts: all
  become: true
  tasks:
    - name: Finalizing | Cleanup package cache (debian and ubuntu)
      tags: always
      ansible.builtin.apt:
        autoclean: true
      changed_when: false
      when: ansible_pkg_mgr == "apt"

    - name: Finalizing | Autoremove orphan packages (debian and ubuntu)
      tags: always
      ansible.builtin.apt:
        autoremove: true
        purge: true
      when: ansible_pkg_mgr == "apt"
