- name: "SSH | {{ ansible_distribution }} | Install openssh-server"
  ansible.builtin.apt:
    name: openssh-server
    state: latest
    update_cache: true
  notify: Restart SSH

- name: "SSH | {{ ansible_distribution }} | Ensure ssh service is enabled and started"
  ansible.builtin.service:
    name: ssh
    enabled: true
    state: started

- name: "SSH | {{ ansible_distribution }} | Deploy sshd_config"
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    backup: true
    validate: /usr/sbin/sshd -t -f %s
  notify: Restart SSH
