branch: main
ansible_cron_minute: "40"
timezone: "Europe/Amsterdam"
dns_servers:
  - "192.168.1.2"
  - "192.168.1.3"

# --------------------------------------------------------------------
# USER CONFIGURATION
# --------------------------------------------------------------------

homelab_user: ashborn
homelab_user_pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEXGrUwai6ZD75n5rPTl06f0gEMtzJU0W8xFnR9YPghE {{ homelab_user }} default"
ansible_user: "{{ homelab_user }}"

# SSH Settings
ssh_port: 22
ssh_users:
  - "{{ homelab_user }}"
  - root

# REQUIRED: Your name for git commits and configurations
# This will be used for git config user.name
git_user_name: "DjCoke"

# standard upgrades
unattended_upgrades: true

# Debugging?
debugging: false

# --------------------------------------------------------------------
# ROLE CONFIGURATION
# --------------------------------------------------------------------
default_roles:
  - base
  - users
  - fonts
  - locale
  - openssh

k3s_roles:
  - k3s_prereq
