---
- name: "System | {{ ansible_distribution }} | Update APT Repos and Upgrade APT Packages"
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: full
    autoremove: true
    autoclean: true
  register: result
  until: result is succeeded
  # This task updates the apt package cache, ensuring it is refreshed.
  # The cache is considered valid for 3600 seconds (1 hour).
  # The task will retry until the cache update succeeds.

- name: "System | {{ ansible_distribution }} | Upgrade all packages"
  ansible.builtin.apt:
    upgrade: yes
    state: latest
  when: unattended_upgrades
  # This task upgrades all installed packages on the system to their latest versions.
  # It only runs if the variable 'keep_packages_updated' is set to true.

- name: "System | {{ ansible_distribution }} | Ensure ansible is the latest version"
  package:
    name: ansible
    state: latest
  # This task ensures that the latest version of Ansible is installed on the host.
  # It will upgrade Ansible if an older version is detected.

- name: "System | {{ ansible_distribution }} | Install System Apps"
  ansible.builtin.apt:
    name:
      - jq
      - open-iscsi
      - dconf-cli
      - python3-psutil
      - smartmontools
      - htop
      - bonnie++
      - unzip
      - lm-sensors
      - htop
      - curl
      - git
      - unzip
      - net-tools
      - acl
      - locales
      - nfs-common
      - multipath-tools
      - scsitools
      - lsscsi
    state: present
  become: true

- name: "System | {{ ansible_distribution }} | Create ansible log file"
  file:
    path: /var/log/ansible.log
    owner: "{{ homelab_user }}"
    group: root
    mode: 0664
    state: touch
  changed_when: False
  # This task creates the Ansible log file at /var/log/ansible.log if it doesn't already exist.
  # The file is owned by the 'homelab_user' user and has permissions set to 0664.
  # The task does not report changes if the file already exists.

- name: "System | {{ ansible_distribution }} | Add logrotate config for ansible log file"
  copy:
    src: files/logrotate
    dest: /etc/logrotate.d/ansible
    owner: root
    group: root
    mode: 0644
  # This task installs a logrotate configuration file for the Ansible log.
  # The configuration file is copied to /etc/logrotate.d/ansible and sets up automatic log rotation.
  # The file is owned by root with permissions set to 0644.

- name: "System | {{ ansible_distribution }} | Remove default ansible directory (/etc/ansible) from host"
  file:
    path: /etc/ansible
    state: absent
  # This task removes the default Ansible directory (/etc/ansible) if it exists.
  # This is useful if you want to avoid using the default configuration directory.

- name: "System | {{ ansible_distribution }} | Install qemu-guest-agent if running in Proxmox VM"
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present
  when: proxmox_vm | bool
  notify: System | Reboot
  # This task installs the 'qemu-guest-agent' package and triggers a reboot if the installation was successful.
  # The reboot is handled by the 'Ansible Setup | Reboot the node' handler.

- name: "System | {{ ansible_distribution }} | Set hostname to match inventory name"
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"

- name: "System | {{ ansible_distribution }} | Set timezone to defined timezone in group_vars/all"
  community.general.timezone:
    name: "{{ timezone }}"

- name: System | Detecting win32yank
  ansible.builtin.stat:
    path: /usr/local/bin/win32yank.exe
  register: win32yank_installed
  when: ansible_host_environment_is_wsl

- name: "System | Install win32yank.exe"
  when:
    - ansible_host_environment_is_wsl
    - not win32yank_installed.stat.exists
  block:
    - name: Download win32yank zip
      ansible.builtin.get_url:
        url: https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
        dest: /tmp/win32yank.zip
        mode: "0755"

    - name: System | Unzip win32yank.exe
      ansible.builtin.unarchive:
        src: /tmp/win32yank.zip
        dest: /tmp
        mode: "0755"

    - name: System | Copy win32yank into path
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/win32yank.exe
        dest: /usr/local/bin/win32yank.exe
        mode: "0755"
      become: true

    - name: System | Remove tmp files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/win32yank.zip
        - /tmp/win32yank.exe
