- name: Users | root | Ensure account is locked (except proxmox_server)
  user:
    name: root
    password_lock: true
  when: not proxmox_server
  tags: users

- name: Users | root | Ensure account is not locked in proxmox (Web GUI)
  user:
    name: root
    password_lock: false
  when: proxmox_server
  tags: users
